services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
